name: CI (Linux)

on:
  push:
    branches: [main, rel]
  pull_request:
    branches: [main, rel]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0

      - name: Install ESLint
        run: npm install --global eslint@8.57.0

      - name: Install GTS
        run: npm install --global gts

      - name: Install VScode Test
        run: npm install --global vscode-test

      - name: Install dependencies
        run: npm install

      - name: Build the extension
        run: npm run compile

      - name: Lint
        run: gts lint
